[linters]
enable = [
    "asciicheck",
    # "bodyclose",
    "cyclop",
    "deadcode",
    # "depguard",
    "dogsled",
    "dupl",
    "durationcheck",
    "errcheck",
    "errorlint",
    "exportloopref",
    "exhaustive",
    "forbidigo",
    "forcetypeassert",
    "funlen",
    "gci",
    "gochecknoglobals",
    "gochecknoinits",
    "gocognit",
    "goconst",
    "gocritic",
    "gocyclo",
    "godot",
    "godox",
    "goerr113",
    "gomnd",
    "goprintffuncname",
    "gosec",
    "gosimple",
    "govet",
    "ifshort",
    "importas",
    "ineffassign",
    "lll",
    "makezero",
    "misspell",
    "nakedret",
    "nestif",
    "nilerr",
    "nlreturn",
    "noctx",
    "nolintlint",
    "prealloc",
    "predeclared",
    # "rowserrcheck",
    # "sqlclosecheck",
    "staticcheck",
    "structcheck",
    "stylecheck",
    "testpackage",
    "typecheck",
    "unconvert",
    "unparam",
    "unused",
    "varcheck",
    "wastedassign",
    "whitespace",
    "wrapcheck",
    "wsl"]

[issues]
exclude-rules = [
    {
        path = "_test.go",
        linters = [
            "dupl",
            "errcheck",
            "gocyclo",
            "gosec"]}]
fix = true
max-issues-per-linter = 0
max-same-issues = 0
# new = true

linter-settings = {
    gci = {
        local-prefixes = "github.com/meanguy/gode"},
    nolintlint = {
        allow-leading-space = false,
        allow-unused = false,
        require-explanation = true,
        require-specific = true}}
